### ISSUE TITLE
suspicious hasattr(f, name)

### ISSUE THREAD

**Issue by nishio** [icoxfog417/pykintone#26]
https://github.com/icoxfog417/pykintone/blob/master/pykintone/structure_field.py#L75

`hasattr(f, name)` (notice it is not `hasattr(f, "name")`) is always False because of `name = ""` in L81

**Comment by uchan-nos** [comment]
I think one more bug is there.

`basename(file.name)` -> `basename(f.name)`, isn't it?

**Comment by uchan-nos** [comment]
Anyway, some tests for file uploading should be added before fixing the bug.

**Comment by nishio** [comment]
>Anyway, some tests for file uploading should be added before fixing the bug.

Here it is
https://github.com/icoxfog417/pykintone/blob/master/tests/test_model.py#L142

However I didn't understand how to upload files yet.

**Comment by uchan-nos** [comment]
I discovered a procedure to upload a file:

1. Upload a file to kintone and get a "file key".
2. Attach the file key to a record's file field.

This is a patch to `File.upload` method:

```Python
    @classmethod
    def upload(cls, file_or_path, api, mime_type, file_name=""):
        url = cls.API_ROOT.format(api.account.domain)

        def _upload(file):
            if file_name:
                n = file_name
            else:
                n = "" if not hasattr(file, "name") else basename(file.name)

            f = {"file": (n, file, mime_type)}
            r = api._request("FILE", url, params_or_data=f)
            return n, r
```

And this is example program to attach a file to a record of test application.

```Python
import pykintone
import pykintone.model
from pykintone.structure_field import File


class TestAppRecord(pykintone.model.kintoneModel):
    def __init__(self):
        super().__init__()
        self.attachfile = None


def add_file_to_field(model, field_name, uploaded_file):
    field_value = getattr(model, field_name)

    if field_value is None:
        files = [uploaded_file]
    elif isinstance(field_value, File):
        files = [field_value, uploaded_file]
    elif isinstance(field_value, list):
        files = field_value + [uploaded_file]
    else:
        raise RuntimeError('This should not happen')

    setattr(model, field_name, files)


def main():
    kinapp = pykintone.load('account.yaml').app(app_name='test')
    record = kinapp.get(102)
    model = record.model(TestAppRecord)

    uploaded_file = File.upload('LICENSE', kinapp, 'text/plain')
    add_file_to_field(model, 'attachfile', uploaded_file)

    res = kinapp.update(model)
    print(res.ok, res.message, res.error)


if __name__ == '__main__':
    main()
```

**Comment by uchan-nos** [comment]
I'll push a pull request later!

**Comment by uchan-nos** [comment]
The bug inside `_upload` method may become apparent when you are uploading a file with no extension.
This is because python-requests can't determine the mime-type for a file with no extension, and kintone can't handle a file with no mime-type.

**Comment by uchan-nos** [comment]
After patching #30, the above example to upload a file looks slightly different:

Before `uploaded_file = File.upload('LICENSE', kinapp, 'text/plain')`

After `uploaded_file = File.upload('LICENSE', kinapp, mime_type='text/plain')`
