### ISSUE TITLE
I need correct handling of Application#requests_opstions

### ISSUE THREAD

**Issue by nishio** [icoxfog417/pykintone#3]
In some subdomains we have to set `cert` option when we call `requests.get`, `requests.post` and so on.
I found the variable `requests_opstions`, but the constructor doesn't take a value for it nor the variable is not passed to `requests.*`. 
https://github.com/icoxfog417/pykintone/blob/master/pykintone/application.py#L15

I think it is nice to have. Thanks.

**Comment by icoxfog417** [comment]
It is implemented in Pull #4 .

As stated in commit message, it is minimal implementation. Some requests options are useful to be set in setting file (ex. `proxies`). But to deal with it will affect to not a little area (ex. `kintoneService`).

So first of all, I take YAGNI strategy.

**Comment by nishio** [comment]
Thank you for the implementation! It helps me a lot!

**Comment by nishio** [comment]
This minimal impl. doesn't work well.
Here is a patch.
https://gist.github.com/nishio/3e9a0345631e91e19c7c

**Comment by icoxfog417** [comment]
Sorry, there are terrible typo...
Could you send me your patch as pull request?
