### ISSUE TITLE
I want to get the items I set in the app's checkbox.

### ISSUE THREAD

**Issue by mturu1976** [icoxfog417/pykintone#35]
The code below in REST cURL can get the CHECK_BOX I set up, but how can I get it in pykintone?

`curl -X GET 'https://[instans_name].cybozu.com/k/v1/form.json?app=43' -H 'X-Cybozu-API-Token:[token]'`

> {"type":"CHECK_BOX","label":"ジャンル","noLabel":"false","code":"genre","required":"false","options":["AAA","BBB","CCC"],"defaultValue":[]},

**Comment by icoxfog417** [comment]
You can get checkbox values by preparing the array field.

https://github.com/icoxfog417/pykintone/blob/master/tests/test_model.py#L19

And use `app.get` to load the record to model.

https://github.com/icoxfog417/pykintone/blob/master/tests/test_model.py#L67
